ALTER TABLE counterparties ADD COLUMN IF NOT EXISTS contact_person VARCHAR(300);
ALTER TABLE counterparties ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE counterparties ADD COLUMN IF NOT EXISTS email VARCHAR(200);
ALTER TABLE counterparties ADD COLUMN IF NOT EXISTS bank_name VARCHAR(300);
