-- Expand document categories: add APPENDIX, LOCAL_ESTIMATE, DESIGN_DOC, COMMERCIAL_PROPOSAL, CERTIFICATE, SCHEDULE, TECHNICAL
ALTER TABLE documents DROP CONSTRAINT IF EXISTS chk_document_category;

ALTER TABLE documents ADD CONSTRAINT chk_document_category CHECK (
  category IS NULL OR category IN (
    'CONTRACT', 'APPENDIX', 'ESTIMATE', 'LOCAL_ESTIMATE', 'SPECIFICATION',
    'DRAWING', 'DESIGN_DOC', 'PERMIT', 'ACT', 'INVOICE', 'COMMERCIAL_PROPOSAL',
    'PROTOCOL', 'CORRESPONDENCE', 'CERTIFICATE', 'SCHEDULE', 'PHOTO', 'REPORT',
    'TECHNICAL', 'OTHER'
  )
);
