import {
  Home,
  FolderKanban,
  FileSignature,
  Calculator,
  ClipboardList,
  MessageSquare,
  FileInput,
  AlertCircle,
  GitPullRequest,
  CalendarDays,
  GitBranch,
  Network,
  PenTool,
  FileText,
  FolderOpen,
  FileCheck,
  ArrowLeftRight,
  Download,
  Banknote,
  Wallet,
  Receipt,
  CreditCard,
  TrendingDown,
  Landmark,
  Hash,
  Target,
  DollarSign,
  Briefcase,
  FileSearch,
  Scale,
  ShoppingCart,
  Warehouse,
  Boxes,
  ClipboardCheck,
  BookOpen,
  ListOrdered,
  Users,
  UsersRound,
  Clock,
  HardHat,
  ScrollText,
  UserPlus,
  Calendar,
  ShieldCheck,
  ListChecks,
  Award,
  Search,
  BadgeCheck,
  Ruler,
  Truck,
  Wrench,
  Fuel,
  Cpu,
  Thermometer,
  AlertTriangle,
  HardDrive,
  Box,
  Smartphone,
  Camera,
  Eye,
  CheckSquare,
  Send,
  Shield,
  LifeBuoy,
  BarChart3,
  FileBarChart,
  TrendingUp,
  Activity,
  Trophy,
  TableProperties,
  Settings,
  UserCog,
  Plug,
  Bell,
  MessageCircle,
  Star,
  Phone,
  Key,
  Webhook,
  LayoutDashboard,
  Cog,
  Layers,
  CheckCircle,
  FolderTree,
  Route,
  RefreshCw,
  CalendarClock,
  Database,
  History,
  Bug,
  Store,
  Building2,
} from 'lucide-react';
import type React from 'react';
import { t } from '@/i18n';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface NavItem {
  id: string;
  label: string;
  icon: React.ElementType;
  href: string;
  badge?: number;
}

export interface NavGroup {
  id: string;
  title: string;
  icon: React.ElementType;
  items: NavItem[];
}

// ---------------------------------------------------------------------------
// Helpers — use getters so t() is called at access time (locale-aware)
// ---------------------------------------------------------------------------

function navGroup(id: string, icon: React.ElementType, items: NavItem[]): NavGroup {
  return {
    get title() { return t(`navigation.groups.${id}`); },
    id,
    icon,
    items,
  };
}

function navItem(id: string, icon: React.ElementType, href: string, badge?: number): NavItem {
  const item: NavItem = {
    get label() { return t(`navigation.items.${id}`); },
    id,
    icon,
    href,
  };
  if (badge !== undefined) item.badge = badge;
  return item;
}

// ---------------------------------------------------------------------------
// Navigation structure
// ---------------------------------------------------------------------------

export const navigation: NavGroup[] = [
  navGroup('home', Home, [
    navItem('dashboard', Home, '/'),
  ]),
  navGroup('precon', Target, [
    navItem('crm-leads', Target, '/crm/leads'),
    navItem('fin-opportunities', Briefcase, '/portfolio/opportunities'),
    navItem('site-assessments', Search, '/site-assessments'),
    navItem('projects-list', FolderKanban, '/projects'),
    navItem('counterparties', Building2, '/counterparties'),
  ]),
  navGroup('pricing', Calculator, [
    navItem('specifications', ClipboardList, '/specifications'),
    navItem('estimates', Calculator, '/estimates'),
    navItem('estimates-pricing-databases', TableProperties, '/estimates/pricing/databases'),
    navItem('estimates-pricing-rates', TableProperties, '/estimates/pricing/rates'),
    navItem('estimates-pricing-calc', TableProperties, '/estimates/pricing/calculate'),
    navItem('spec-analogs', ArrowLeftRight, '/specifications/analogs'),
    navItem('spec-analog-requests', RefreshCw, '/specifications/analog-requests'),
  ]),
  navGroup('economics', Wallet, [
    navItem('fin-budgets', Wallet, '/budgets'),
    navItem('fin-fm', TableProperties, '/financial-models'),
    navItem('fin-commercial-proposals', FileText, '/commercial-proposals'),
    navItem('fin-tenders', FileSearch, '/portfolio/tenders'),
    navItem('fin-bid-comparison', Scale, '/portfolio/bid-comparison'),
    navItem('CONTRACTS', FileSignature, '/contracts'),
    navItem('fin-procurement', ShoppingCart, '/procurement'),
  ]),
  navGroup('pm', Network, [
    navItem('pm-rfis', MessageSquare, '/pm/rfis'),
    navItem('pm-submittals', FileInput, '/pm/submittals'),
    navItem('pm-issues', AlertCircle, '/pm/issues'),
    navItem('pm-change-events', GitPullRequest, '/change-management/events'),
    navItem('pm-change-orders', GitPullRequest, '/change-management/orders'),
    navItem('pm-tasks-board', Activity, '/tasks'),
    navItem('pm-tasks-list', ClipboardList, '/tasks/list'),
    navItem('pm-tasks-gantt', CalendarDays, '/tasks/gantt'),
    navItem('pm-calendar', Calendar, '/calendar'),
    navItem('pm-wbs', Network, '/planning/wbs'),
    navItem('pm-gantt', CalendarDays, '/planning/gantt'),
    navItem('pm-baseline', CalendarClock, '/planning/baseline'),
    navItem('pm-resources', Users, '/planning/resources'),
    navItem('pm-evm', TrendingUp, '/planning/evm'),
    navItem('pm-workflows', GitBranch, '/workflow/templates'),
    navItem('pm-workflow-active', Activity, '/workflow/instances'),
    navItem('pm-workflow-designer', PenTool, '/workflow/designer'),
    navItem('pm-monte-carlo', Activity, '/monte-carlo'),
  ]),
  navGroup('DOCUMENTS', FileText, [
    navItem('doc-list', FileText, '/documents'),
    navItem('cde-docs', FolderOpen, '/cde/documents'),
    navItem('cde-transmittals', Send, '/cde/transmittals'),
    navItem('pto-docs', ClipboardList, '/pto/documents'),
    navItem('pto-ks6-calendar', CalendarClock, '/pto/ks6-calendar'),
    navItem('pto-permits', BadgeCheck, '/pto/work-permits'),
    navItem('pto-lab', Search, '/pto/lab-tests'),
    navItem('russian-docs', ScrollText, '/russian-docs/list'),
    navItem('russian-docs-create', FileCheck, '/russian-docs/create'),
    navItem('russian-ks2', FileCheck, '/russian-docs/ks2'),
    navItem('russian-ks3', FileCheck, '/russian-docs/ks3'),
    navItem('data-import', Download, '/data-exchange/import'),
    navItem('data-export', ArrowLeftRight, '/data-exchange/export'),
    navItem('data-mapping', GitBranch, '/data-exchange/mapping'),
    navItem('russian-sbis', FileText, '/russian-docs/sbis'),
    navItem('russian-edo', Send, '/russian-docs/edo'),
    navItem('data-1c-config', Database, '/data-exchange/1c-config'),
    navItem('data-1c-logs', History, '/data-exchange/1c-logs'),
  ]),
  navGroup('finance', Banknote, [
    navItem('fin-invoices', Receipt, '/invoices'),
    navItem('fin-payments', CreditCard, '/payments'),
    navItem('fin-cashflow', TrendingDown, '/cash-flow'),
    navItem('fin-accounting', Landmark, '/accounting'),
    navItem('fin-chart', ListOrdered, '/accounting/chart'),
    navItem('fin-journal', BookOpen, '/accounting/journal'),
    navItem('fin-assets', Box, '/accounting/assets'),
    navItem('fin-cost-codes', Hash, '/cost-management/codes'),
    navItem('fin-cost-budget', Target, '/cost-management/budget'),
    navItem('fin-commitments', ClipboardCheck, '/cost-management/commitments'),
    navItem('fin-forecast', TrendingUp, '/cost-management/forecast'),
    navItem('fin-cost-cashflow', TrendingDown, '/cost-management/cashflow'),
    navItem('fin-rev-contracts', DollarSign, '/revenue/contracts'),
    navItem('fin-rev-periods', CalendarDays, '/revenue/periods'),
    navItem('fin-rev-dashboard', BarChart3, '/revenue/dashboard'),
    navItem('fin-price-coefficients', Calculator, '/price-coefficients'),
    navItem('fin-tax-risk', AlertTriangle, '/tax-risk'),
  ]),
  navGroup('SUPPLY', Warehouse, [
    navItem('wh-locations', Warehouse, '/warehouse/locations'),
    navItem('wh-stock', Boxes, '/warehouse/stock'),
    navItem('wh-materials', Boxes, '/warehouse/materials'),
    navItem('wh-movements', ArrowLeftRight, '/warehouse/movements'),
    navItem('wh-inventory', ClipboardCheck, '/warehouse/inventory'),
    navItem('wh-stock-limits', AlertTriangle, '/warehouse/stock-limits'),
    navItem('wh-stock-alerts', Bell, '/warehouse/stock-alerts'),
    navItem('ops-daily', BookOpen, '/operations/daily-logs'),
    navItem('ops-work-orders', ListOrdered, '/operations/work-orders'),
    navItem('ops-dashboard', BarChart3, '/operations/dashboard'),
    navItem('ops-dispatch-calendar', CalendarDays, '/operations/dispatch-calendar'),
    navItem('ops-dispatch', Truck, '/dispatch/orders'),
    navItem('ops-routes', Route, '/dispatch/routes'),
  ]),
  navGroup('hr', Users, [
    navItem('hr-employees', Users, '/employees'),
    navItem('hr-crew', UsersRound, '/crew'),
    navItem('hr-timesheets', Clock, '/timesheets'),
    navItem('hr-safety', HardHat, '/safety'),
    navItem('hr-ru-contracts', ScrollText, '/hr-russian/employment-contracts'),
    navItem('hr-ru-orders', ClipboardList, '/hr-russian/personnel-orders'),
    navItem('hr-ru-staffing', ListOrdered, '/hr-russian/staffing'),
    navItem('hr-ru-timesheets', Clock, '/hr-russian/timesheets'),
    navItem('hr-recruitment', UserPlus, '/recruitment/applicants'),
    navItem('hr-jobs', Briefcase, '/recruitment/jobs'),
    navItem('hr-leave', Calendar, '/leave/requests'),
    navItem('hr-crew-timesheets', Clock, '/hr/crew-timesheets'),
    navItem('hr-crew-entries', Clock, '/hr/crew-time-entries'),
    navItem('hr-crew-calendar', Calendar, '/hr/crew-time-calendar'),
    navItem('hr-timesheet-pivot', BarChart3, '/hr/timesheet-pivot'),
    navItem('hr-leave-allocations', CalendarClock, '/leave/allocations'),
    navItem('hr-leave-types', FileText, '/leave/types'),
    navItem('hr-payroll', Banknote, '/payroll'),
    navItem('hr-payroll-calc', Calculator, '/payroll/calculate'),
    navItem('hr-self-employed', UserPlus, '/self-employed'),
    navItem('hr-se-payments', CreditCard, '/self-employed/payments'),
    navItem('hr-se-registries', ClipboardList, '/self-employed/registries'),
  ]),
  navGroup('MAINTENANCE', Wrench, [
    navItem('maint-dashboard', LayoutDashboard, '/maintenance/dashboard'),
    navItem('maint-requests', Wrench, '/maintenance/requests'),
    navItem('maint-equipment', Cog, '/maintenance/equipment'),
  ]),
  navGroup('legal', Scale, [
    navItem('legal-cases', Scale, '/legal/cases'),
    navItem('legal-templates', FileText, '/legal/templates'),
  ]),
  navGroup('crm', Target, [
    navItem('crm-dashboard', LayoutDashboard, '/crm/dashboard'),
  ]),
  navGroup('kep', Shield, [
    navItem('kep-certificates', Shield, '/kep/certificates'),
    navItem('kep-signing', PenTool, '/kep/signing-requests'),
  ]),
  navGroup('DESIGN', Layers, [
    navItem('design-versions', Layers, '/design/versions'),
    navItem('design-reviews', CheckCircle, '/design/reviews'),
    navItem('design-sections', FolderTree, '/design/sections'),
  ]),
  navGroup('QUALITY', ShieldCheck, [
    navItem('qa-quality', ShieldCheck, '/quality'),
    navItem('qa-defects', Bug, '/defects'),
    navItem('qa-punchlist', ListChecks, '/punchlist/items'),
    navItem('qa-punchlist-dash', BarChart3, '/punchlist/dashboard'),
    navItem('qa-permits', FileCheck, '/regulatory/permits'),
    navItem('qa-licenses', Award, '/regulatory/licenses'),
    navItem('qa-inspections', Search, '/regulatory/inspections'),
    navItem('qa-reg-dashboard', BarChart3, '/regulatory/dashboard'),
    navItem('qa-tolerance-rules', Ruler, '/quality/tolerance-rules'),
    navItem('qa-tolerance-checks', CheckSquare, '/quality/tolerance-checks'),
    navItem('qa-certificates', Award, '/quality/certificates'),
    navItem('qa-reporting-calendar', CalendarClock, '/regulatory/reporting-calendar'),
  ]),
  navGroup('EQUIPMENT', Truck, [
    navItem('eq-vehicles', Truck, '/fleet'),
    navItem('eq-maintenance', Wrench, '/fleet/maintenance'),
    navItem('eq-fuel', Fuel, '/fleet/fuel'),
    navItem('eq-iot-devices', Cpu, '/iot/devices'),
    navItem('eq-iot-sensors', Thermometer, '/iot/sensors'),
    navItem('eq-iot-alerts', AlertTriangle, '/iot/alerts'),
  ]),
  navGroup('site', HardHat, [
    navItem('site-daily', BookOpen, '/daily-log'),
    navItem('site-ks2', FileCheck, '/ks2'),
    navItem('site-ks3', FileCheck, '/ks3'),
    navItem('site-m29', HardDrive, '/m29'),
    navItem('site-bim-models', Box, '/bim/models'),
    navItem('site-bim-packages', FolderOpen, '/bim/design-packages'),
    navItem('site-bim-clash', Eye, '/bim/clash-detection'),
    navItem('site-mobile-reports', Smartphone, '/mobile/reports'),
    navItem('site-mobile-photos', Camera, '/mobile/photos'),
    navItem('site-mobile-dash', BarChart3, '/mobile/dashboard'),
  ]),
  navGroup('closeout', CheckSquare, [
    navItem('co-commissioning', CheckSquare, '/closeout/commissioning'),
    navItem('co-handover', Send, '/closeout/handover'),
    navItem('co-warranty', Shield, '/closeout/warranty'),
    navItem('co-dashboard', BarChart3, '/closeout/dashboard'),
    navItem('co-support', LifeBuoy, '/support/tickets'),
    navItem('co-support-dash', BarChart3, '/support/dashboard'),
  ]),
  navGroup('analytics', BarChart3, [
    navItem('an-dashboards', BarChart3, '/analytics'),
    navItem('an-reports', FileBarChart, '/reports'),
    navItem('an-kpi', TrendingUp, '/kpi'),
    navItem('an-monitoring', Activity, '/monitoring'),
    navItem('an-kpi-achievements', Trophy, '/analytics/kpi-achievements'),
    navItem('an-bonus', Calculator, '/analytics/bonus-calculations'),
    navItem('an-audit-pivot', FileBarChart, '/analytics/audit-pivot'),
    navItem('an-project-charts', TrendingUp, '/analytics/project-charts'),
    navItem('an-search', Search, '/search'),
    navItem('an-ai', MessageCircle, '/ai-assistant'),
  ]),
  navGroup('admin', Settings, [
    navItem('adm-settings', Settings, '/settings'),
    navItem('adm-users', UserCog, '/admin/users'),
    navItem('adm-permissions', Shield, '/admin/permissions'),
    navItem('adm-integrations', Plug, '/admin/integrations'),
    navItem('adm-integrations-hub', Plug, '/integrations'),
    navItem('adm-portal', UsersRound, '/portal'),
    navItem('adm-notifications', Bell, '/notifications', 3),
    navItem('adm-messenger', MessageCircle, '/messaging', 5),
    navItem('adm-calls', Phone, '/messaging/calls'),
    navItem('adm-favorites', Star, '/messaging/favorites'),
    navItem('adm-api-keys', Key, '/settings/api-keys'),
    navItem('adm-webhooks', Webhook, '/settings/webhooks'),
    navItem('adm-subscription', CreditCard, '/settings/subscription'),
    navItem('adm-marketplace', Store, '/marketplace'),
  ]),
];
